name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  google_format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.2'
        architecture: x64
    - run: ./gradlew verifyFormatting
